### PR TITLE
use a proper struct to decode the config

### LINKED ISSUE #193: Unsuccessful cast when setting configuration from VS Code
This cast

https://github.com/prometheus-community/promql-langserver/blob/356efaf3f31e909b86fb593011524df8ad5c1363/langserver/config.go#L45

always fails, which makes it impossible to set configuration from VS Code.

To actually work, there first would need to be a cast to `map[string]interface{}` and then a second cast for the `promql` field.

### PR DESCRIPTION
**Pull request by Nexucis**
fix #193

### CODE REVIEW

**Comment by slrtbtfs** [comment]
So what's happening here is:

* The gopls lib unmarshals the JSON received by the client.
* This code marshals and unmarshals part of it again, as a somewhat weird way of typecasting.

While I'm not principally against this, it should at least be documented, what is going on and why it has been done this way.

**Comment by Nexucis** [comment]
as a comment or as a markdown documentation ?

**Comment by slrtbtfs** [comment]
Comment should be fine.

**Comment by Nexucis** [comment]
done

File: langserver/config.go [hunk 1]
```diff
@@ -36,27 +46,25 @@ func (s *server) DidChangeConfiguration(ctx context.Context, params *protocol.Di
...
-	setting := params.Settings
+	config := localLSPConfiguration{}
 
-	// the struct expected is the following
-	// promql:
-	//   url: http://
-	//   interval: 3w
-	m, ok := setting.(map[string]map[string]string)
-	if !ok {
+	// In order to avoid a loop other different interface coming from the general settings
```
Comment (slrtbtfs) [inline langserver/config.go:51]: This comment is a bit confusing and has a couple of language issues. Maybe something like

```
Go doesn't provide an easy way to cast nested maps into structs.

As a workaround, the configuration is first converted back to the JSON that was provided by the client and then marshalled back into the expected structure of the settings.

If you are reading this code and are aware of a better solution to do this, feel free to submit a PR.
```

Note that, while I don't like it, I didn't find a better way to do this either.

File: langserver/config.go [hunk 2]
```diff
@@ -36,27 +46,25 @@ func (s *server) DidChangeConfiguration(ctx context.Context, params *protocol.Di
...
 		return nil
 	}
-	config, ok := m["promql"]
-	if !ok {
+	if err := json.Unmarshal(rawData, &config); err != nil {
 		// nolint: errcheck
 		s.client.LogMessage(ctx, &protocol.LogMessageParams{
 			Type:    protocol.Error,
-			Message: fmt.Sprint("promQL key not found"),
+			Message: fmt.Sprint("unexpected format of the configuration"),
```
Comment (slrtbtfs) [inline langserver/config.go:67]:
```suggestion
			Message: fmt.Sprint("unexpected configuration format"),
```

Can you include the error message from the json package here, e.g. via `Wrapf`?

File: langserver/config.go (hunk 1 above)
Comment (Nexucis) [reply langserver/config.go:51]: oh don't worry I don't like it too lol

File: langserver/config.go (hunk 2 above)
Comment (Nexucis) [reply langserver/config.go:67]: I don't see the point of using `Wrapf` since the error is not used afterward and also since the `Message` is taking a string and not an error.

We could just do that instead : 


```go
Message: fmt.Sprintf("unexpected configuration format: %s",err),

Comment (slrtbtfs) [reply langserver/config.go:67]: That'd be equivalent to 

```
Message: errors.Wrap(err, "unexpected configuration format").Error(),
```

I like this version slightly better, but there isn't a significant difference.
